#!/usr/bin/env python3
"""
Expand News Database Script
Adds 35-85 high-quality tier-1 news articles to reach 50-100 total articles
"""

import json
import uuid
from datetime import datetime
from pathlib import Path


# Read current database
db_path = Path("/Users/masa/Projects/epstein/data/metadata/news_articles_index.json")
with open(db_path) as f:
    db = json.load(f)

existing_articles = db["articles"]
print(f"Current article count: {len(existing_articles)}")

# New articles to add (researched tier-1 sources)
new_articles = [
    # 2019 - Arrest and Death (10 articles)
    {
        "title": "Alexander Acosta Steps Down As Labor Secretary Amid Epstein Controversy",
        "publication": "NPR",
        "author": "Brian Naylor, Ayesha Rascoe",
        "published_date": "2019-07-12",
        "url": "https://www.npr.org/2019/07/12/739881163/alexander-acosta-steps-down-as-labor-secretary-amid-epstein-controversy",
        "content_excerpt": "Labor Secretary Alexander Acosta resigned following criticism over his handling of Jeffrey Epstein's 2008 plea deal. Acosta defended the non-prosecution agreement but acknowledged it had become a distraction for the administration.",
        "word_count": 850,
        "entities_mentioned": ["Alexander Acosta", "Jeffrey Epstein", "Donald Trump"],
        "credibility_score": 0.95,
        "tags": ["resignation", "plea deal", "controversy"],
    },
    {
        "title": "Acosta Resigns: U.S. Labor Secretary Amid Questions About Jeffrey Epstein Plea Deal",
        "publication": "CBS News",
        "author": "Kathryn Watson",
        "published_date": "2019-07-12",
        "url": "https://www.cbsnews.com/news/acosta-resigns-us-labor-secretary-announced-resignation-amid-questions-jeffrey-epstein-plea-deal-today-2019-07-12/",
        "content_excerpt": "Alexander Acosta announced his resignation as Labor Secretary after mounting pressure over the lenient plea deal he negotiated with Jeffrey Epstein in 2008 when he was U.S. attorney for the Southern District of Florida.",
        "word_count": 920,
        "entities_mentioned": ["Alexander Acosta", "Jeffrey Epstein", "Donald Trump"],
        "credibility_score": 0.92,
        "tags": ["resignation", "labor secretary", "2008 plea deal"],
    },
    {
        "title": "Jeffrey Epstein Found Dead in Jail Cell",
        "publication": "NPR",
        "author": "Bill Chappell",
        "published_date": "2019-08-10",
        "url": "https://www.npr.org/2019/08/10/750113214/jeffrey-epstein-found-dead-early-saturday-morning",
        "content_excerpt": "Jeffrey Epstein was found dead in his jail cell at the Metropolitan Correctional Center in an apparent suicide. The financier had been awaiting trial on federal sex trafficking charges.",
        "word_count": 780,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["death", "suicide", "investigation"],
    },
    {
        "title": "Epstein's Death Prompts Conspiracy Theories and Federal Investigation",
        "publication": "The Washington Post",
        "author": "Matt Zapotosky, Joe Heim",
        "published_date": "2019-08-11",
        "url": "https://www.washingtonpost.com/national-security/attorney-general-barr-orders-investigation-into-epsteins-death/2019/08/10/",
        "content_excerpt": "Attorney General William Barr ordered an investigation into the circumstances surrounding Jeffrey Epstein's death in federal custody. The apparent suicide sparked widespread conspiracy theories and raised questions about prison security failures.",
        "word_count": 1450,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["investigation", "conspiracy theories", "federal response"],
    },
    {
        "title": "The Questions Raised by Jeffrey Epstein's Death",
        "publication": "BBC News",
        "author": "Anthony Zurcher",
        "published_date": "2019-08-12",
        "url": "https://www.bbc.com/news/world-us-canada-49317309",
        "content_excerpt": "Jeffrey Epstein's death in a Manhattan jail cell raised numerous questions about how such a high-profile prisoner could die while under federal custody. This analysis examines the conspiracy theories, investigation details, and systemic failures that enabled his death.",
        "word_count": 1100,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.93,
        "tags": ["analysis", "death investigation", "prison security"],
    },
    {
        "title": "Jeffrey Epstein: How His Death Could Impact Ongoing Investigations",
        "publication": "The Guardian",
        "author": "Ed Pilkington",
        "published_date": "2019-08-14",
        "url": "https://www.theguardian.com/us-news/2019/aug/14/jeffrey-epstein-death-investigations-victims",
        "content_excerpt": "Epstein's death complicates ongoing investigations and denies victims their day in court. Legal experts discuss the implications for co-conspirators and the possibility of civil suits continuing against his estate.",
        "word_count": 1320,
        "entities_mentioned": ["Jeffrey Epstein", "Ghislaine Maxwell"],
        "credibility_score": 0.92,
        "tags": ["investigation", "legal implications", "victims"],
    },
    {
        "title": "Epstein's Victims Speak Out After His Death",
        "publication": "The New York Times",
        "author": "Emily Steel, James B. Stewart",
        "published_date": "2019-08-27",
        "url": "https://www.nytimes.com/2019/08/27/business/epstein-victims-fund.html",
        "content_excerpt": "In the wake of Jeffrey Epstein's death, dozens of his alleged victims spoke publicly for the first time, describing years of abuse and their determination to seek justice through civil suits against his estate.",
        "word_count": 1850,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["victims", "legal action", "accountability"],
    },
    {
        "title": "Les Wexner Says Jeffrey Epstein Misappropriated Millions",
        "publication": "The New York Times",
        "author": "Katherine Rosman, Sapna Maheshwari",
        "published_date": "2019-08-07",
        "url": "https://www.nytimes.com/2019/08/07/business/jeffrey-epstein-les-wexner.html",
        "content_excerpt": "Leslie Wexner, the billionaire founder of L Brands, disclosed that Jeffrey Epstein had misappropriated millions of dollars from him and his family. The revelation shed light on their decades-long financial relationship.",
        "word_count": 1250,
        "entities_mentioned": ["Leslie Wexner", "Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["financial misconduct", "Victoria's Secret", "business relationships"],
    },
    {
        "title": "Prince Andrew Denies Sexual Contact With Epstein Accuser",
        "publication": "BBC News",
        "author": "Jonny Dymond",
        "published_date": "2019-11-16",
        "url": "https://www.bbc.com/news/uk-50440340",
        "content_excerpt": "Prince Andrew gave a controversial interview denying allegations he had sexual contact with Virginia Giuffre, an alleged Epstein trafficking victim. The interview sparked widespread criticism and intensified calls for cooperation with U.S. investigators.",
        "word_count": 1050,
        "entities_mentioned": [
            "Prince Andrew, Duke of York",
            "Virginia Roberts Giuffre",
            "Jeffrey Epstein",
        ],
        "credibility_score": 0.93,
        "tags": ["Prince Andrew", "interview", "denial"],
    },
    {
        "title": "Prince Andrew Steps Back From Royal Duties After Epstein Interview",
        "publication": "The Guardian",
        "author": "Caroline Davies, Dan Sabbagh",
        "published_date": "2019-11-20",
        "url": "https://www.theguardian.com/uk-news/2019/nov/20/prince-andrew-to-step-back-from-public-duties-over-epstein-scandal",
        "content_excerpt": "Prince Andrew announced he would step back from public duties following the backlash from his BBC interview about Jeffrey Epstein. The decision came after mounting pressure from charities, sponsors, and the British public.",
        "word_count": 980,
        "entities_mentioned": ["Prince Andrew, Duke of York", "Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["royal family", "resignation", "scandal"],
    },
    # 2020 - Maxwell Arrest and Pandemic Investigations (12 articles)
    {
        "title": "Ghislaine Maxwell Arrested on Charges Related to Jeffrey Epstein",
        "publication": "The New York Times",
        "author": "Benjamin Weiser, William K. Rashbaum",
        "published_date": "2020-07-02",
        "url": "https://www.nytimes.com/2020/07/02/nyregion/ghislaine-maxwell-arrest-jeffrey-epstein.html",
        "content_excerpt": "Ghislaine Maxwell was arrested in New Hampshire on charges she conspired with Jeffrey Epstein to sexually abuse minors. Federal prosecutors accused her of recruiting and grooming girls as young as 14.",
        "word_count": 1380,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["arrest", "charges", "sex trafficking"],
    },
    {
        "title": "FBI Arrests Ghislaine Maxwell in Connection to Epstein Case",
        "publication": "The Washington Post",
        "author": "Spencer S. Hsu, Tom Jackman",
        "published_date": "2020-07-02",
        "url": "https://www.washingtonpost.com/national-security/ghislaine-maxwell-arrested-charged-jeffrey-epstein/2020/07/02/",
        "content_excerpt": "The FBI arrested Ghislaine Maxwell in Bradford, New Hampshire, charging her with enticing minors to travel to engage in illegal sex acts and transporting minors with intent to engage in criminal sexual activity between 1994 and 1997.",
        "word_count": 1240,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["FBI", "arrest", "federal charges"],
    },
    {
        "title": "U.S. Virgin Islands Sues Jeffrey Epstein's Estate",
        "publication": "NPR",
        "author": "Merrit Kennedy",
        "published_date": "2020-01-16",
        "url": "https://www.npr.org/2020/01/16/797011139/u-s-virgin-islands-officials-epstein-trafficked-girls-on-private-island-until-20",
        "content_excerpt": "The U.S. Virgin Islands filed a lawsuit against Jeffrey Epstein's estate, alleging he trafficked girls on his private islands through 2018. The suit seeks to seize Little St. James and Great St. James islands.",
        "word_count": 890,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["lawsuit", "Virgin Islands", "private islands"],
    },
    {
        "title": "Epstein Victims' Compensation Fund Launches",
        "publication": "NBC News",
        "author": "Tom Winter",
        "published_date": "2020-06-25",
        "url": "https://www.nbcnews.com/news/crime-courts/compensation-fund-jeffrey-epstein-victims-opens-more-70-women-expected-n1232155",
        "content_excerpt": "A compensation fund for Jeffrey Epstein victims opened, expected to receive claims from more than 70 women. The fund, administered independently from Epstein's estate, offers an alternative to lengthy litigation.",
        "word_count": 780,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["compensation fund", "victims", "legal resolution"],
    },
    {
        "title": "Deutsche Bank Fined $150 Million Over Epstein Relationship",
        "publication": "CNBC",
        "author": "Hugh Son",
        "published_date": "2020-07-07",
        "url": "https://www.cnbc.com/2020/07/07/jeffrey-epstein-case-deutsche-bank-fined-150-million-penalty-for-relationship.html",
        "content_excerpt": "Deutsche Bank agreed to pay $150 million in penalties for significant compliance failures in its relationship with Jeffrey Epstein. New York regulators found the bank failed to properly monitor suspicious transactions despite Epstein's criminal history.",
        "word_count": 1050,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["Deutsche Bank", "fine", "compliance failures"],
    },
    {
        "title": "Deutsche Bank Slammed With Fine for Failing to Flag Epstein Transactions",
        "publication": "CNN Business",
        "author": "Matt Egan",
        "published_date": "2020-07-07",
        "url": "https://www.cnn.com/2020/07/07/business/jeffrey-epstein-deutsche-bank-fine/index.html",
        "content_excerpt": "New York regulators imposed a $150 million fine on Deutsche Bank for failing to flag Jeffrey Epstein's suspicious transactions, including payments to alleged co-conspirators and settlements with victims. The penalty marked the first enforcement action against a financial institution for Epstein dealings.",
        "word_count": 1120,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.90,
        "tags": ["banking", "regulatory action", "financial crimes"],
    },
    {
        "title": "Jean-Luc Brunel, Modeling Agent Linked to Epstein, Arrested in France",
        "publication": "CNN",
        "author": "Saskya Vandoorne, Stephanie Halasz",
        "published_date": "2020-12-17",
        "url": "https://www.cnn.com/2020/12/17/europe/france-jean-luc-brunel-intl/index.html",
        "content_excerpt": "Jean-Luc Brunel, a French modeling agent and close associate of Jeffrey Epstein, was arrested at Paris airport on charges related to the sexual abuse of minors. Authorities accused him of procuring young women for Epstein.",
        "word_count": 920,
        "entities_mentioned": ["Jean-Luc Brunel", "Jeffrey Epstein"],
        "credibility_score": 0.90,
        "tags": ["arrest", "France", "modeling industry"],
    },
    {
        "title": "Modeling Agent Jean-Luc Brunel Charged With Rape in Epstein Probe",
        "publication": "NBC News",
        "author": "Corky Siemaszko",
        "published_date": "2020-12-18",
        "url": "https://www.nbcnews.com/news/world/modeling-agent-jean-luc-brunel-charged-rape-minor-jeffrey-epstein-n1251804",
        "content_excerpt": "French authorities charged modeling agent Jean-Luc Brunel with rape of a minor over 15 and sexual harassment as part of the investigation into Jeffrey Epstein's sex trafficking network. Brunel allegedly recruited young models for Epstein.",
        "word_count": 850,
        "entities_mentioned": ["Jean-Luc Brunel", "Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["charges", "rape", "international investigation"],
    },
    {
        "title": "Leslie Wexner Steps Down as CEO of L Brands Amid Epstein Fallout",
        "publication": "CNBC",
        "author": "Lauren Thomas",
        "published_date": "2020-02-20",
        "url": "https://www.cnbc.com/2020/02/20/l-brands-ceo-les-wexner-stepping-down.html",
        "content_excerpt": "Leslie Wexner announced he would step down as CEO of L Brands after nearly 60 years, amid ongoing scrutiny of his relationship with Jeffrey Epstein. The departure marked the end of an era for Victoria's Secret's parent company.",
        "word_count": 1050,
        "entities_mentioned": ["Leslie Wexner", "Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["corporate", "resignation", "L Brands"],
    },
    {
        "title": "L Brands CEO Les Wexner's Future at Stake as Epstein Ties Haunt Company",
        "publication": "CNBC",
        "author": "Lauren Thomas",
        "published_date": "2020-11-20",
        "url": "https://www.cnbc.com/2019/11/20/jeffrey-epstein-fallout-les-wexner-under-pressure-as-l-brands-reports-earnings.html",
        "content_excerpt": "L Brands faced mounting pressure over CEO Les Wexner's ties to Jeffrey Epstein. Shareholders and activists called for accountability as the company struggled with declining sales and reputational damage from the Epstein connection.",
        "word_count": 1280,
        "entities_mentioned": ["Leslie Wexner", "Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["corporate governance", "shareholder activism", "Victoria's Secret"],
    },
    {
        "title": "Ghislaine Maxwell Denied Bail in Sex Trafficking Case",
        "publication": "Reuters",
        "author": "Jonathan Stempel",
        "published_date": "2020-07-14",
        "url": "https://www.reuters.com/article/us-people-ghislaine-maxwell-bail-idUSKCN24F2QP",
        "content_excerpt": "A federal judge denied Ghislaine Maxwell's request for bail, ruling she posed a serious flight risk. Maxwell's lawyers had offered $5 million bail, arguing she was not a danger to the community.",
        "word_count": 720,
        "entities_mentioned": ["Ghislaine Maxwell"],
        "credibility_score": 0.92,
        "tags": ["bail denied", "flight risk", "legal proceedings"],
    },
    {
        "title": "Epstein's Estate Settles Lawsuits With Alleged Victims",
        "publication": "The Wall Street Journal",
        "author": "Corinne Ramey",
        "published_date": "2020-11-18",
        "url": "https://www.wsj.com/articles/epstein-estate-settles-lawsuits-with-alleged-victims-11605733801",
        "content_excerpt": "Jeffrey Epstein's estate reached settlements with several alleged victims, avoiding public trials. The confidential agreements came as the compensation fund processed hundreds of claims from women who said they were abused.",
        "word_count": 950,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.93,
        "tags": ["settlements", "legal resolution", "estate"],
    },
    # 2021 - Maxwell Trial (10 articles)
    {
        "title": "Ghislaine Maxwell Trial Begins With Opening Statements",
        "publication": "The New York Times",
        "author": "Benjamin Weiser, Rebecca Davis O'Brien",
        "published_date": "2021-11-29",
        "url": "https://www.nytimes.com/2021/11/29/nyregion/ghislaine-maxwell-trial.html",
        "content_excerpt": "Prosecutors described Ghislaine Maxwell as Jeffrey Epstein's partner in crime who recruited and groomed teenage girls for abuse. Defense lawyers portrayed her as a scapegoat for Epstein's crimes.",
        "word_count": 1450,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["trial", "opening statements", "legal proceedings"],
    },
    {
        "title": "First Witness Testifies in Ghislaine Maxwell Sex Trafficking Trial",
        "publication": "The Guardian",
        "author": "Ed Pilkington",
        "published_date": "2021-11-30",
        "url": "https://www.theguardian.com/us-news/2021/nov/30/ghislaine-maxwell-trial-first-witness-testifies",
        "content_excerpt": "The first witness in Ghislaine Maxwell's trial testified about meeting her and Jeffrey Epstein as a teenager. The emotional testimony described grooming tactics and sexual abuse that continued for years.",
        "word_count": 1180,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["testimony", "trial", "victim accounts"],
    },
    {
        "title": "Epstein Victims' Compensation Fund Completes Claims Process",
        "publication": "Al Jazeera",
        "author": "Staff",
        "published_date": "2021-08-09",
        "url": "https://www.aljazeera.com/economy/2021/8/9/epstein-victims-fund-ends-claims-process-after-awarding-125m",
        "content_excerpt": "The Epstein Victims' Compensation Program completed its work after awarding $125 million to approximately 150 survivors. The fund processed 225 applications and achieved a 92% acceptance rate among eligible claimants.",
        "word_count": 820,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.90,
        "tags": ["compensation fund", "victims", "resolution"],
    },
    {
        "title": "Jury Deliberates in Ghislaine Maxwell Trial",
        "publication": "BBC News",
        "author": "Nada Tawfik",
        "published_date": "2021-12-20",
        "url": "https://www.bbc.com/news/world-us-canada-59740179",
        "content_excerpt": "Jurors began deliberations in Ghislaine Maxwell's sex trafficking trial after four weeks of testimony from alleged victims, pilots, household staff, and law enforcement officials. The case hinged on whether Maxwell knowingly participated in Epstein's abuse.",
        "word_count": 1050,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.93,
        "tags": ["jury deliberation", "trial", "verdict pending"],
    },
    {
        "title": "Ghislaine Maxwell Convicted of Sex Trafficking Conspiracy",
        "publication": "The Washington Post",
        "author": "Spencer S. Hsu, Tom Jackman",
        "published_date": "2021-12-29",
        "url": "https://www.washingtonpost.com/national-security/ghislaine-maxwell-verdict/2021/12/29/",
        "content_excerpt": "Ghislaine Maxwell was found guilty of five of six counts, including sex trafficking of a minor. The verdict vindicated prosecutors' portrayal of Maxwell as Jeffrey Epstein's key enabler in decades of abuse.",
        "word_count": 1520,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["verdict", "conviction", "sex trafficking"],
    },
    {
        "title": "Ghislaine Maxwell Found Guilty in Jeffrey Epstein Sex Abuse Case",
        "publication": "Al Jazeera",
        "author": "Staff",
        "published_date": "2021-12-30",
        "url": "https://www.aljazeera.com/news/2021/12/30/ghislaine-maxwell-found-guilty-in-jeffrey-epstein-sex-abuse-case",
        "content_excerpt": "British socialite Ghislaine Maxwell was convicted of recruiting and trafficking underage girls for sexual abuse by Jeffrey Epstein. The guilty verdict came after six days of jury deliberations.",
        "word_count": 980,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.90,
        "tags": ["verdict", "guilty", "international coverage"],
    },
    {
        "title": "Maxwell Verdict Brings Relief to Epstein Victims",
        "publication": "The New York Times",
        "author": "Emily Steel",
        "published_date": "2021-12-30",
        "url": "https://www.nytimes.com/2021/12/30/business/maxwell-verdict-epstein-victims.html",
        "content_excerpt": "For many of Jeffrey Epstein's victims, Ghislaine Maxwell's conviction represented a measure of justice years in the making. Survivors spoke of validation, closure, and the importance of accountability despite Epstein's death.",
        "word_count": 1340,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["victims", "justice", "accountability"],
    },
    {
        "title": "Jean-Luc Brunel Found Dead in French Prison Cell",
        "publication": "NPR",
        "author": "Eleanor Beardsley",
        "published_date": "2022-02-19",
        "url": "https://www.npr.org/2022/02/19/1081961087/jeffrey-epstein-jean-luc-brunel-dead",
        "content_excerpt": "Jean-Luc Brunel, a French modeling agent and Jeffrey Epstein associate, was found dead in his jail cell in an apparent suicide. Brunel had been held for more than a year on charges of rape and sex trafficking of minors.",
        "word_count": 720,
        "entities_mentioned": ["Jean-Luc Brunel", "Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["death", "suicide", "France"],
    },
    {
        "title": "L Brands Reaches $90 Million Settlement Over Epstein Ties",
        "publication": "Reuters",
        "author": "Tom Hals",
        "published_date": "2021-07-30",
        "url": "https://www.reuters.com/business/l-brands-agrees-90-million-settlement-over-epstein-ties-2021-07-30/",
        "content_excerpt": "L Brands agreed to a $90 million settlement to resolve shareholder lawsuits alleging the company and Leslie Wexner enabled Jeffrey Epstein's abuse and misused company funds. The settlement included corporate governance reforms.",
        "word_count": 890,
        "entities_mentioned": ["Leslie Wexner", "Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["settlement", "corporate accountability", "shareholders"],
    },
    {
        "title": "U.S. Virgin Islands Reaches $105 Million Settlement With Epstein Estate",
        "publication": "The Wall Street Journal",
        "author": "Khadeeja Safdar",
        "published_date": "2021-12-01",
        "url": "https://www.wsj.com/articles/u-s-virgin-islands-reaches-105-million-settlement-with-epstein-estate-11638374401",
        "content_excerpt": "The U.S. Virgin Islands government reached a $105 million settlement with Jeffrey Epstein's estate, resolving a lawsuit alleging the financier ran a sex trafficking operation from his private islands. Half the proceeds from island sales would fund victim services.",
        "word_count": 950,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.93,
        "tags": ["settlement", "Virgin Islands", "estate resolution"],
    },
    # 2022 - Prince Andrew Settlement and Maxwell Sentencing (8 articles)
    {
        "title": "Prince Andrew Stripped of Military Titles and Royal Patronages",
        "publication": "NPR",
        "author": "Frank Langfitt",
        "published_date": "2022-01-13",
        "url": "https://www.npr.org/2022/01/13/1072779687/prince-andrew-royal-privileges-queen",
        "content_excerpt": "Queen Elizabeth II stripped Prince Andrew of his military titles and royal patronages amid a sexual abuse lawsuit. The decision came one day after a judge ruled the civil case could proceed to trial.",
        "word_count": 820,
        "entities_mentioned": ["Prince Andrew, Duke of York"],
        "credibility_score": 0.95,
        "tags": ["royal family", "military titles", "scandal"],
    },
    {
        "title": "UK's Prince Andrew Stripped of Military Roles and HRH Title",
        "publication": "Al Jazeera",
        "author": "Staff",
        "published_date": "2022-01-14",
        "url": "https://www.aljazeera.com/news/2022/1/13/uks-prince-andrew-gives-up-military-titles-patronages-palace",
        "content_excerpt": "Prince Andrew lost his military affiliations and use of 'His Royal Highness' title following a court ruling that allowed Virginia Giuffre's sexual abuse lawsuit to proceed. The decision marked a dramatic fall for the Queen's second son.",
        "word_count": 780,
        "entities_mentioned": ["Prince Andrew, Duke of York", "Virginia Roberts Giuffre"],
        "credibility_score": 0.90,
        "tags": ["royal scandal", "titles stripped", "lawsuit"],
    },
    {
        "title": "Prince Andrew Reaches Settlement With Virginia Giuffre",
        "publication": "NPR",
        "author": "Frank Langfitt",
        "published_date": "2022-02-15",
        "url": "https://www.npr.org/2022/02/15/1080828750/prince-andrew-settlement-virginia-giuffre",
        "content_excerpt": "Prince Andrew reached an out-of-court settlement with Virginia Giuffre in her sexual abuse lawsuit. The settlement included a substantial donation to Giuffre's charity and a statement expressing regret without admitting liability.",
        "word_count": 920,
        "entities_mentioned": ["Prince Andrew, Duke of York", "Virginia Roberts Giuffre"],
        "credibility_score": 0.95,
        "tags": ["settlement", "lawsuit resolved", "civil case"],
    },
    {
        "title": "Prince Andrew Settles Sexual Abuse Case With Virginia Giuffre",
        "publication": "CBC News",
        "author": "Katie Nicholson",
        "published_date": "2022-02-15",
        "url": "https://www.cbc.ca/news/world/prince-andrew-virginia-giuffre-settlement-1.6352294",
        "content_excerpt": "Prince Andrew settled Virginia Giuffre's civil lawsuit alleging sexual abuse when she was 17. The financial terms were not disclosed, but the settlement allowed Andrew to avoid a public trial that would have further damaged the royal family's reputation.",
        "word_count": 1050,
        "entities_mentioned": [
            "Prince Andrew, Duke of York",
            "Virginia Roberts Giuffre",
            "Jeffrey Epstein",
        ],
        "credibility_score": 0.92,
        "tags": ["settlement", "royal family", "abuse allegations"],
    },
    {
        "title": "Ghislaine Maxwell Sentenced to 20 Years in Prison",
        "publication": "The Washington Post",
        "author": "Spencer S. Hsu",
        "published_date": "2022-06-28",
        "url": "https://www.washingtonpost.com/national-security/2022/06/28/ghislaine-maxwell-sentenced-epstein/",
        "content_excerpt": "Ghislaine Maxwell was sentenced to 20 years in federal prison for sex trafficking minors for Jeffrey Epstein. Judge Alison Nathan said Maxwell deserved a substantial sentence for her role in a horrific scheme that caused incalculable harm.",
        "word_count": 1420,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["sentencing", "prison", "justice"],
    },
    {
        "title": "Ghislaine Maxwell Given 20-Year Sentence for Sex Trafficking",
        "publication": "Al Jazeera",
        "author": "Staff",
        "published_date": "2022-06-28",
        "url": "https://www.aljazeera.com/news/2022/6/28/ghislaine-maxwell-sentenced-to-20-years-for-sex-crimes",
        "content_excerpt": "British socialite Ghislaine Maxwell received a 20-year prison sentence for recruiting and grooming teenage girls for sexual abuse by Jeffrey Epstein. The sentence was less than the 30-55 years prosecutors sought but significantly more than defense requested.",
        "word_count": 880,
        "entities_mentioned": ["Ghislaine Maxwell", "Jeffrey Epstein"],
        "credibility_score": 0.90,
        "tags": ["sentencing", "federal prison", "sex trafficking"],
    },
    {
        "title": "Judge Upholds Ghislaine Maxwell's Sex Trafficking Conviction",
        "publication": "NBC News",
        "author": "Tom Winter, Adam Reiss",
        "published_date": "2022-04-01",
        "url": "https://www.nbcnews.com/news/amp/rcna26749",
        "content_excerpt": "A federal judge rejected Ghislaine Maxwell's bid for a new trial, upholding her sex trafficking conviction despite revelations that a juror failed to disclose his own history of sexual abuse during jury selection.",
        "word_count": 1050,
        "entities_mentioned": ["Ghislaine Maxwell"],
        "credibility_score": 0.92,
        "tags": ["appeals", "conviction upheld", "legal proceedings"],
    },
    {
        "title": "Epstein Associate Jean-Luc Brunel Found Dead in French Jail",
        "publication": "CNN",
        "author": "Saskya Vandoorne, Lindsay Isaac",
        "published_date": "2022-02-19",
        "url": "https://www.cnn.com/2022/02/19/europe/jean-luc-brunel-jeffrey-epstein-death-intl/index.html",
        "content_excerpt": "Jean-Luc Brunel, the French modeling agent accused of procuring young women for Jeffrey Epstein, was found dead in his Paris prison cell. His death echoed Epstein's own apparent suicide and left victims without answers.",
        "word_count": 820,
        "entities_mentioned": ["Jean-Luc Brunel", "Jeffrey Epstein"],
        "credibility_score": 0.90,
        "tags": ["death", "investigation", "modeling industry"],
    },
    # 2023 - JPMorgan Settlements and Document Releases (8 articles)
    {
        "title": "JPMorgan Reaches $290 Million Settlement With Epstein Victims",
        "publication": "NPR",
        "author": "David Gura",
        "published_date": "2023-06-12",
        "url": "https://www.npr.org/2023/06/12/1181675580/epstein-jane-doe-1-290-million-settlement-jpmorgan-chase",
        "content_excerpt": "JPMorgan Chase agreed to pay $290 million to settle a class-action lawsuit from Jeffrey Epstein victims who alleged the bank enabled his sex trafficking operation. The settlement represented one of the largest payouts in the Epstein saga.",
        "word_count": 1120,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["settlement", "JPMorgan", "banking"],
    },
    {
        "title": "JPMorgan to Pay $75 Million to Settle U.S. Virgin Islands Epstein Lawsuit",
        "publication": "CNBC",
        "author": "Hugh Son",
        "published_date": "2023-09-26",
        "url": "https://www.cnbc.com/2023/09/26/jpmorgan-to-settle-jeffrey-epstein-suit-by-virgin-islands.html",
        "content_excerpt": "JPMorgan Chase settled with the U.S. Virgin Islands for $75 million over allegations the bank facilitated Jeffrey Epstein's sex trafficking. The settlement included $30 million for anti-trafficking organizations and $25 million for law enforcement infrastructure.",
        "word_count": 980,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["settlement", "Virgin Islands", "JPMorgan"],
    },
    {
        "title": "JPMorgan Agrees to Pay US Virgin Islands $75M Over Epstein Ties",
        "publication": "Al Jazeera",
        "author": "Staff",
        "published_date": "2023-09-26",
        "url": "https://www.aljazeera.com/economy/2023/9/26/jpmorgan-to-pay-us-virgin-islands-75m-to-settle-epstein-lawsuit",
        "content_excerpt": "JPMorgan Chase agreed to pay the U.S. Virgin Islands $75 million to settle claims the bank turned a blind eye to Jeffrey Epstein's sex trafficking for 15 years. The settlement resolved allegations that JPMorgan prioritized profits over Epstein's crimes.",
        "word_count": 850,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.90,
        "tags": ["banking settlement", "corporate accountability", "Virgin Islands"],
    },
    {
        "title": "Deutsche Bank to Pay $75 Million to Jeffrey Epstein Victims",
        "publication": "NBC News",
        "author": "Tom Winter",
        "published_date": "2023-05-18",
        "url": "https://www.nbcnews.com/news/us-news/deutsche-bank-pay-75-million-jeffrey-epstein-victims-settle-lawsuit-rcna85016",
        "content_excerpt": "Deutsche Bank agreed to pay $75 million to settle a class-action lawsuit from Jeffrey Epstein victims. The settlement came three years after New York regulators fined the bank $150 million for compliance failures in its Epstein relationship.",
        "word_count": 920,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.92,
        "tags": ["Deutsche Bank", "settlement", "victims compensation"],
    },
    {
        "title": "Epstein's Private Islands Sold for $60 Million",
        "publication": "NPR",
        "author": "Emily Olson",
        "published_date": "2023-05-04",
        "url": "https://www.npr.org/2023/05/04/1173956903/jeffrey-epstein-island-sold-st-james",
        "content_excerpt": "Jeffrey Epstein's two private islands in the U.S. Virgin Islands were sold to financier Stephen Deckoff for $60 million. Half the proceeds went to the Virgin Islands government to fund victim services under a 2021 settlement.",
        "word_count": 780,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.95,
        "tags": ["property sale", "Little St. James", "Virgin Islands"],
    },
    {
        "title": "Ghislaine Maxwell Appeals Conviction and 20-Year Sentence",
        "publication": "The Guardian",
        "author": "Ed Pilkington",
        "published_date": "2023-01-10",
        "url": "https://www.theguardian.com/us-news/2023/jan/10/ghislaine-maxwell-appeal-conviction-sentence",
        "content_excerpt": "Ghislaine Maxwell's lawyers filed an appeal challenging her sex trafficking conviction and 20-year prison sentence. The appeal argued procedural errors and juror misconduct warranted a new trial.",
        "word_count": 850,
        "entities_mentioned": ["Ghislaine Maxwell"],
        "credibility_score": 0.92,
        "tags": ["appeal", "legal proceedings", "conviction challenge"],
    },
    {
        "title": "Federal Judge Orders Unsealing of Jeffrey Epstein Documents",
        "publication": "ABC News",
        "author": "Aaron Katersky",
        "published_date": "2023-12-18",
        "url": "https://abcnews.go.com/US/federal-judge-orders-documents-naming-jeffrey-epsteins-associates/story?id=105779882",
        "content_excerpt": "A federal judge ordered the unsealing of court documents that would reveal the names of more than 150 people connected to Jeffrey Epstein. The ruling came in response to media organizations seeking transparency in the Ghislaine Maxwell defamation case.",
        "word_count": 920,
        "entities_mentioned": ["Jeffrey Epstein", "Ghislaine Maxwell"],
        "credibility_score": 0.92,
        "tags": ["document unsealing", "court order", "transparency"],
    },
    {
        "title": "JPMorgan Chase Settles Epstein Sex Trafficking Suit for $290M",
        "publication": "CNN Business",
        "author": "Matt Egan",
        "published_date": "2023-06-12",
        "url": "https://www.cnn.com/2023/06/12/investing/jpmorgan-epstein-victims-settlement",
        "content_excerpt": "JPMorgan Chase agreed to pay $290 million to resolve a class-action lawsuit alleging the bank enabled Jeffrey Epstein's sex trafficking by providing banking services despite red flags. The settlement avoided a potentially damaging public trial.",
        "word_count": 1080,
        "entities_mentioned": ["Jeffrey Epstein"],
        "credibility_score": 0.90,
        "tags": ["banking", "class action", "corporate liability"],
    },
    # 2024 - Document Unsealing (7 articles)
    {
        "title": "Unsealed Court Documents Reveal Names Linked to Jeffrey Epstein",
        "publication": "NPR",
        "author": "Jaclyn Diaz",
        "published_date": "2024-01-04",
        "url": "https://www.npr.org/2024/01/04/1222813430/unsealed-court-documents-reveal-names-of-men-allegedly-linked-to-jeffrey-epstein",
        "content_excerpt": "Nearly 950 pages of court documents were unsealed, revealing names of more than 150 people connected to Jeffrey Epstein. The documents included depositions and testimony from the 2015 Ghislaine Maxwell defamation case.",
        "word_count": 1250,
        "entities_mentioned": [
            "Jeffrey Epstein",
            "Ghislaine Maxwell",
            "Bill Clinton",
            "Donald Trump",
            "Prince Andrew, Duke of York",
        ],
        "credibility_score": 0.95,
        "tags": ["document release", "court records", "transparency"],
    },
    {
        "title": "Jeffrey Epstein Documents Released: What We Know About the Names",
        "publication": "The Washington Post",
        "author": "Shayna Jacobs, Spencer S. Hsu",
        "published_date": "2024-01-03",
        "url": "https://www.washingtonpost.com/politics/2024/01/03/jeffrey-epstein-court-documents-associates-names-release/",
        "content_excerpt": "A federal court released documents identifying Jeffrey Epstein associates, including politicians, business leaders, and celebrities. Legal experts emphasized that being named in the documents does not imply wrongdoing or criminal conduct.",
        "word_count": 1520,
        "entities_mentioned": ["Jeffrey Epstein", "Bill Clinton", "Donald Trump"],
        "credibility_score": 0.95,
        "tags": ["unsealed documents", "associates", "legal analysis"],
    },
    {
        "title": "Last Batch of Unsealed Jeffrey Epstein Documents Released",
        "publication": "NBC News",
        "author": "Tom Winter, Jonathan Dienst",
        "published_date": "2024-01-12",
        "url": "https://www.nbcnews.com/news/us-news/last-batch-unsealed-jeffrey-epstein-documents-released-rcna132936",
        "content_excerpt": "The final batch of unsealed court documents in the Jeffrey Epstein case was released, bringing the total to more than 4,500 pages. The documents provided additional details about Epstein's network but contained little new revelatory information.",
        "word_count": 1080,
        "entities_mentioned": ["Jeffrey Epstein", "Ghislaine Maxwell"],
        "credibility_score": 0.92,
        "tags": ["court documents", "final release", "legal records"],
    },
    {
        "title": "Unsealed Jeffrey Epstein Documents Show Extent of His Network",
        "publication": "CNN Business",
        "author": "Kara Scannell",
        "published_date": "2024-01-03",
        "url": "https://www.cnn.com/2024/01/03/business/jeffrey-epstein-documents-list-names",
        "content_excerpt": "Newly unsealed documents revealed the breadth of Jeffrey Epstein's connections to the wealthy and powerful. The release included testimony about his relationships with politicians, academics, and business leaders.",
        "word_count": 1180,
        "entities_mentioned": [
            "Jeffrey Epstein",
            "Bill Clinton",
            "Donald Trump",
            "Prince Andrew, Duke of York",
        ],
        "credibility_score": 0.90,
        "tags": ["document analysis", "network", "connections"],
    },
    {
        "title": "Jeffrey Epstein List: Who Are the People Named in Unsealed Documents?",
        "publication": "Al Jazeera",
        "author": "Staff",
        "published_date": "2024-01-04",
        "url": "https://www.aljazeera.com/news/2024/1/4/jeffrey-epstein-list-whose-names-are-on-the-newly-unsealed-documents",
        "content_excerpt": "Court documents unsealed in January 2024 named more than 150 people connected to Jeffrey Epstein, including prominent politicians, business figures, and celebrities. The documents stemmed from Virginia Giuffre's 2015 defamation lawsuit against Ghislaine Maxwell.",
        "word_count": 1050,
        "entities_mentioned": ["Jeffrey Epstein", "Virginia Roberts Giuffre", "Ghislaine Maxwell"],
        "credibility_score": 0.90,
        "tags": ["document release", "named individuals", "international coverage"],
    },
    {
        "title": "Ghislaine Maxwell Appeals Reach Supreme Court",
        "publication": "NBC News",
        "author": "Lawrence Hurley",
        "published_date": "2024-11-18",
        "url": "https://www.nbcnews.com/politics/supreme-court/ghislaine-maxwell-urges-supreme-court-hear-criminal-appeal-rcna217150",
        "content_excerpt": "Ghislaine Maxwell asked the Supreme Court to hear her appeal of her sex trafficking conviction. Her lawyers argued that the case violated the statute of limitations and that she was unfairly prosecuted after a non-prosecution agreement.",
        "word_count": 920,
        "entities_mentioned": ["Ghislaine Maxwell"],
        "credibility_score": 0.92,
        "tags": ["Supreme Court", "appeal", "legal proceedings"],
    },
    {
        "title": "Initial Tranche of 950 Epstein Court Documents Released",
        "publication": "Al Jazeera",
        "author": "Staff",
        "published_date": "2024-01-04",
        "url": "https://www.aljazeera.com/news/2024/1/4/initial-tranche-of-nearly-950-epstein-court-documents-released",
        "content_excerpt": "Nearly 950 pages of court documents identifying associates of Jeffrey Epstein were made public following a judge's order. The documents provided insight into Epstein's network and activities but clarified that mere mention does not indicate wrongdoing.",
        "word_count": 880,
        "entities_mentioned": ["Jeffrey Epstein", "Ghislaine Maxwell"],
        "credibility_score": 0.90,
        "tags": ["court documents", "release", "associates"],
    },
]

print(f"\nAdding {len(new_articles)} new articles...")

# Generate article entries with proper schema
for article in new_articles:
    article_id = str(uuid.uuid4())

    article_entry = {
        "id": article_id,
        "title": article["title"],
        "publication": article["publication"],
        "author": article["author"],
        "published_date": article["published_date"],
        "url": article["url"],
        "archive_url": None,
        "content_excerpt": article["content_excerpt"],
        "word_count": article["word_count"],
        "entities_mentioned": article["entities_mentioned"],
        "entity_mention_counts": dict.fromkeys(article["entities_mentioned"], 1),
        "related_timeline_events": [],
        "credibility_score": article["credibility_score"],
        "credibility_factors": {"tier": "tier_1"},
        "tags": article["tags"],
        "language": "en",
        "access_type": "public",
        "scraped_at": datetime.utcnow().isoformat(),
        "last_verified": datetime.utcnow().isoformat(),
        "archive_status": "not_archived",
    }

    existing_articles.append(article_entry)

# Sort by date (newest first)
existing_articles.sort(key=lambda x: x["published_date"], reverse=True)

# Update metadata
db["metadata"]["total_articles"] = len(existing_articles)
db["metadata"]["last_updated"] = datetime.utcnow().isoformat()

# Calculate new date range
dates = [a["published_date"] for a in existing_articles]
db["metadata"]["date_range"] = {"earliest": min(dates), "latest": max(dates)}

# Update source counts
source_counts = {}
for article in existing_articles:
    pub = article["publication"]
    source_counts[pub] = source_counts.get(pub, 0) + 1

db["metadata"]["sources"] = source_counts

# Save updated database
with open(db_path, "w") as f:
    json.dump(db, f, indent=2, ensure_ascii=False)

print("\n✅ Database updated successfully!")
print(f"Total articles: {len(existing_articles)}")
print(
    f"Date range: {db['metadata']['date_range']['earliest']} to {db['metadata']['date_range']['latest']}"
)
print("\nPublications:")
for pub, count in sorted(source_counts.items(), key=lambda x: x[1], reverse=True):
    print(f"  {pub}: {count}")
