# Fish completion for epstein-cli
# Generated by argcomplete

function __fish_epstein_cli_complete
    set -lx COMP_LINE (commandline -cp)
    set -lx COMP_POINT (commandline -C)
    set -lx COMP_TYPE
    if set -q _ARC_DEBUG
        epstein-cli 8>&1 9>&2 1>&9 2>&1
    else
        epstein-cli 8>&1 9>&2 1>/dev/null 2>&1
    end
end

complete -c epstein-cli -f -a '(__fish_epstein_cli_complete)'
