#!/usr/bin/env python3
"""
Pydantic Data Quality Audit Script

Validates all entity data against Pydantic models and generates a comprehensive report.

Usage:
    python scripts/validation/run_pydantic_audit.py

    # With detailed errors:
    python scripts/validation/run_pydantic_audit.py --verbose

Output:
    - Console summary
    - PYDANTIC_VALIDATION_REPORT.md (detailed report)
    - pydantic_validation_errors.json (machine-readable errors)
"""

import json
import sys
import os
from pathlib import Path
from datetime import datetime
from typing import Dict, List

# Add project root to path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

# Enable Pydantic validation
os.environ['USE_PYDANTIC'] = 'true'

from server.services.entity_service import EntityService
from server.models import Entity, EntityBiography, EntityTag


def generate_markdown_report(
    validation_stats: Dict,
    sample_errors: List[Dict],
    output_path: Path
) -> None:
    """Generate markdown validation report"""

    report = f"""# Pydantic Validation Report

**Generated**: {datetime.now().isoformat()}
**Data Source**: entity_statistics.json, entity_biographies.json, entity_tags.json, entity_network.json

## Summary

- **Total Entities**: {validation_stats['total_entities']}
- **Valid Entities**: {validation_stats['valid_entities']}
- **Failed Entities**: {validation_stats['failed_entities']}
- **Success Rate**: {validation_stats['success_rate'] * 100:.2f}%
- **Total Validation Errors**: {validation_stats['total_errors']}

## Validation Results

### Success Breakdown
- ✅ **Entities Passing Validation**: {validation_stats['valid_entities']}/{validation_stats['total_entities']} ({validation_stats['success_rate'] * 100:.2f}%)
- ❌ **Entities Failing Validation**: {validation_stats['failed_entities']}/{validation_stats['total_entities']}

### Common Error Patterns

"""

    # Group errors by type
    error_types = {}
    for error in sample_errors:
        error_msg = error['error']
        # Extract error type from Pydantic error message
        if 'validation error' in error_msg.lower():
            error_type = "Validation Error"
        elif 'field required' in error_msg.lower():
            error_type = "Missing Required Field"
        elif 'type' in error_msg.lower():
            error_type = "Type Mismatch"
        else:
            error_type = "Other"

        error_types[error_type] = error_types.get(error_type, 0) + 1

    for error_type, count in sorted(error_types.items(), key=lambda x: x[1], reverse=True):
        report += f"- **{error_type}**: {count} occurrences\n"

    report += f"""

## Sample Validation Errors

Below are the first 10 validation errors for debugging:

"""

    for i, error in enumerate(sample_errors[:10], 1):
        report += f"""
### Error {i}: {error['entity']}

**Error Count**: {error['error_count']} field(s) failed validation

**Error Details**:
```
{error['error']}
```

---
"""

    report += """

## Recommendations

Based on validation results:

1. **Data Quality Issues**: Review failed entities and fix data quality issues
2. **Schema Mismatches**: Update Pydantic models to match actual data structure
3. **Migration Strategy**: Fix data issues before enabling Pydantic in production

## Next Steps

1. Review sample errors above
2. Fix data quality issues in source JSON files
3. Re-run validation: `python scripts/validation/run_pydantic_audit.py`
4. Enable Pydantic in production: `export USE_PYDANTIC=true`

---

*Generated by Pydantic Data Quality Audit Script*
"""

    with open(output_path, 'w') as f:
        f.write(report)


def main():
    """Run Pydantic data quality audit"""
    import argparse

    parser = argparse.ArgumentParser(description='Run Pydantic data quality audit')
    parser.add_argument('--verbose', action='store_true', help='Show detailed errors')
    args = parser.parse_args()

    print("=" * 80)
    print("Pydantic Data Quality Audit")
    print("=" * 80)
    print()

    # Initialize entity service (will trigger validation)
    data_path = project_root / "data"
    print(f"Loading data from: {data_path}")
    print()

    service = EntityService(data_path)

    # Get validation report
    report = service.get_validation_report()

    if not report['enabled']:
        print("ERROR: Pydantic validation not enabled!")
        print("Set USE_PYDANTIC=true environment variable")
        sys.exit(1)

    # Print summary
    print("\n" + "=" * 80)
    print("VALIDATION SUMMARY")
    print("=" * 80)
    print(f"Total Entities:        {report['total_entities']}")
    print(f"Valid Entities:        {report['valid_entities']}")
    print(f"Failed Entities:       {report['failed_entities']}")
    print(f"Success Rate:          {report['success_rate'] * 100:.2f}%")
    print(f"Total Errors:          {report['total_errors']}")
    print()

    # Show sample errors if verbose
    if args.verbose and report['errors']:
        print("\n" + "=" * 80)
        print("SAMPLE VALIDATION ERRORS (First 5)")
        print("=" * 80)
        for i, error in enumerate(report['errors'][:5], 1):
            print(f"\n--- Error {i}: {error['entity']} ---")
            print(f"Error Count: {error['error_count']} field(s) failed")
            print(f"Details:\n{error['error'][:500]}...")  # Truncate long errors

    # Generate markdown report
    report_path = project_root / "PYDANTIC_VALIDATION_REPORT.md"
    generate_markdown_report(report, report['errors'], report_path)
    print(f"\n✅ Detailed report saved to: {report_path}")

    # Save errors to JSON for machine processing
    errors_json_path = project_root / "pydantic_validation_errors.json"
    with open(errors_json_path, 'w') as f:
        json.dump({
            'summary': {
                'total_entities': report['total_entities'],
                'valid_entities': report['valid_entities'],
                'failed_entities': report['failed_entities'],
                'success_rate': report['success_rate']
            },
            'errors': report['errors']
        }, f, indent=2)
    print(f"✅ Error details saved to: {errors_json_path}")

    # Exit status
    print()
    if report['success_rate'] == 1.0:
        print("🎉 SUCCESS: All entities passed validation!")
        sys.exit(0)
    elif report['success_rate'] >= 0.95:
        print("⚠️  WARNING: >95% entities valid, but some issues found")
        sys.exit(0)
    else:
        print(f"❌ FAILURE: Only {report['success_rate'] * 100:.1f}% entities valid")
        print("   Review errors and fix data quality issues")
        sys.exit(1)


if __name__ == '__main__':
    main()
